version: 2.1
orbs:
  terraform-orb: aeternity/terraform-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1.2
jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  command-tests:
    docker:
      - image: aeternity/infrastructure:v2.12.4
    steps:
      - checkout
      - run:
          name: Setup environment secrets
          command: mkdir /secrets && echo "VAULT_ADDR" >  /secrets/VAULT_ADDR
      - terraform-orb/terraform_init
      - terraform-orb/terraform_validate
      - terraform-orb/terraform_plan

workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters:
            tags:
              only: /.*/
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          orb-name: aeternity/terraform-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
