version: 2.1
orbs:
  terraform-orb: aeternity/terraform-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  command-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # "greet" is a sample command packaged with this orb config.
      # This sample integration test will run as long as the greet command exists. Once you remove the greet command you should remove this line.
      # Push new changes first, before adding new tests to your config.
      # - terraform-orb/greet
workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters:
            tags:
              only: /.*/
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          orb-name: aeternity/terraform-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
